services:
  db:
    image: mysql:8.0
    container_name: innovatech_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: innovatech_db # Base de datos compartida o puedes crear múltiples
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql # Persistencia de datos para que no se borren al apagar
    ports:
      - "3306:3306"
    networks:
      - innovatech_network

  back_ventas:
    build:
      # La ruta exacta donde pusiste el Dockerfile
      context: ./back-Ventas_SpringBoot/Springboot-API-REST 
    container_name: innovatech_back_ventas
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/innovatech_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8081:8080" # Tu PC usará el 8081, internamente el contenedor usa el 8080
    networks:
      - innovatech_network

  back_despachos:
    build:
      # La ruta exacta donde pusiste el Dockerfile
      context: ./back-Despachos_SpringBoot/Springboot-API-REST-DESPACHO
    container_name: innovatech_back_despachos
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/innovatech_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8082:8080" # Tu PC usará el 8082 para no chocar con el de ventas
    networks:
      - innovatech_network

  frontend:
    build:
      context: ./front_despacho
    container_name: innovatech_frontend
    depends_on:
      - back_ventas
      - back_despachos
    ports:
      - "3000:8080" # <-- Aquí está el cambio clave
    networks:
      - innovatech_network

volumes:
  db_data: # Declaración del volumen nombrado

networks:
  innovatech_network:
    driver: bridge