name: Innovatech CI-CD Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  compile-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Descargar codigo del repositorio
      uses: actions/checkout@v4

    - name: Configurar Java JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'

    - name: Compilar Backend Ventas
      run: |
        cd back-Ventas_SpringBoot/Springboot-API-REST
        mvn clean package -DskipTests

    - name: Compilar Backend Despachos
      run: |
        cd back-Despachos_SpringBoot/Springboot-API-REST-DESPACHO
        mvn clean package -DskipTests

    - name: Validar Sintaxis de Docker Compose
      run: docker compose config
